spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rahul?usessl=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.id.new_generator_mappings: false
server:
  port: 8081
  servlet:
    context-path: /rahul/
swagger:
    enabled: true

